// Generated by https://quicktype.io

export interface MyMood {
    mensaje: string;
}

export interface View {
    result: Enviado;
}

export interface Enviado {
    Enviadas: number;
}


export interface DataGrafic {
    result: Result[];
}

export interface Result {
    Motivados:   number;
    Productivos: number;
    Aburridos:   number;
    Presionados: number;
    Enfadados:   number;
    Totales:     number;
}

