// Generated by https://quicktype.io

export interface Noticia {
    result: Result[];
}

export interface Result {
    Nombre:        string;
    imagenUsuario: string;
    Descripcion:   string;
    Archivo:       string;
    fecha:         null | string;
}
