import { StyleSheet, Text } from 'react-native';

export const styles = StyleSheet.create({

    Text:{
        width:193,
        fontSize:20,
        lineHeight:24.61,
        color:'#093C5D',
        fontWeight:'700',
        textAlign:'center'
    },
    containerGraphics:{
        width:'100%',
        height:540.39,
        backgroundColor:'#FFFFFF',
        marginTop:50,
        borderTopEndRadius:50,
        borderTopStartRadius:50,
        borderBottomEndRadius:20,
        alignItems:'center',
    },
    SubText:{
        fontSize:21,
        lineHeight:24.61,
        color:'#093C5D'
    },
    graphicsContainer:{
        flexDirection:'row',
        marginTop:30
    },
    button:{
        backgroundColor:'#FEC104',
        width:100,
        height:41.14,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:20,
        marginTop:-90
    },
    buttonText:{
        color:'#FFFFFF',
        fontSize:16,
        fontWeight:'700',
        lineHeight:18.75
    },
    moodButton:{
        backgroundColor:'#093C5D',
        width:140.36,
        height:50.93,
        borderRadius:50,
        marginLeft:10,
        marginVertical:5,
        alignItems:'center',
        flexDirection:'row',
        justifyContent:'space-evenly'
        
    },
    moddText:{
        marginTop:3,
        color:'#FFFFFF',
        fontSize:14,
        fontWeight:'500',
        lineHeight:12.89,
    },
    moodColor:{
        width:15,
        height:15,
        borderRadius:100,
        marginLeft:5
    },
    moodNumber:{
        fontSize:10,
        fontWeight:'400',
        lineHeight:11.72,
        color:'#FFFFFF',
        marginRight:5
    },
    grafic:{
        width:175.54,
        height:175.84
    },
    graficText:{
        color:"#093C5D",
        textAlign:'center',
        top:'-49%'
    }
    
});