import { StyleSheet, Text } from 'react-native';

export const styles = StyleSheet.create({

    Text:{
        width:193,
        fontSize:20,
        lineHeight:24.61,
        color:'#093C5D',
        fontWeight:'700',
        textAlign:'center',
        marginTop:'0%',
        marginBottom:'2%'
    },
    containerGraphics:{
        width:'100%',
        flex:1,
        backgroundColor:'#FFFFFF',
        borderTopEndRadius:50,
        borderTopStartRadius:50,
        alignItems:'center',
        marginTop:'2%'
    },
    SubText:{
        fontSize:21,
        lineHeight:24.61,
        color:'#093C5D'
    },
    graphicsContainer:{
        flexDirection:'row',
    },
    button:{
        backgroundColor:'#FEC104',
        width:'27%',
        height:'7%',
        justifyContent:'center',
        alignItems:'center',
        borderRadius:20,
        marginTop:'-26%'
    },
    buttonText:{
        color:'#FFFFFF',
        fontSize:16,
        fontWeight:'700',
        lineHeight:18.75
    },
    moodButton:{
        backgroundColor:'#093C5D',
        width:140.36,
        height:'11%',
        borderRadius:50,
        marginLeft:10,
        marginVertical:'3%',
        alignItems:'center',
        flexDirection:'row',
        justifyContent:'space-around',
        alignContent:'center',
    
        
    },
    moddText:{
        marginTop:3,
        color:'#FFFFFF',
        fontSize:14,
        fontWeight:'500',
        lineHeight:12.89,
        textAlign:'center',
        marginLeft:10
    },
    moodColor:{
        width:15,
        height:15,
        borderRadius:100,
        marginLeft:13
    },
    moodNumber:{
        fontSize:10,
        fontWeight:'400',
        lineHeight:11.72,
        color:'#FFFFFF',
        marginRight:15,
        marginLeft:10,
    },
    graficText:{
        color:"#093C5D",
        textAlign:'center',
        top:'-49%'
    }
    
});